HomeActions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("all/<slug:name_slug>/", views.actions, name="actions"),
]

edxcare/urls.py
from django.conf import settings
from django.conf.urls.static import static

from .views import index,aboutus,resources,contactus
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('about/',aboutus,name='aboutus'),
    path('resources/',resources,name='resources'),
    path('contactus/',contactus,name='contactus'),
    path('solutions/',include('HomeActions.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HomeActions/models.py
from django.db import models
from autoslug import AutoSlugField
from django.urls import reverse

class HomeActions(models.Model):
    """A typical class defining a model, derived from the Model class."""
    # Fields
    name = models.CharField(max_length=500)
    name_slug=AutoSlugField(populate_from='name')
    description = models.TextField()
    icon_class=models.CharField(max_length=100,default='not assigned')
    hex_color=models.CharField(max_length=20,default='#fc5a03')
    

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse('actions', args=[self.name_slug])


class ActionBullet(models.Model):
    Action = models.ForeignKey(HomeActions, default=None, on_delete=models.CASCADE)
    bulletpoint = models.CharField(max_length=500)

    def __str__(self):
        return str(self.Action)

class CustomerResponse(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    whatsapp_number=models.CharField(max_length=20)
    is_interested=models.BooleanField()
    details=models.TextField(blank=True)
    service_required=models.ForeignKey(HomeActions,default=None,on_delete=models.CASCADE)

HomeActions/forms.py
from django import forms
from django import forms
from django.db import models
from django import forms
from .models import CustomerResponse

class CustomerResponseForm(forms.ModelForm):
    class Meta:
        model=CustomerResponse
        fields=['name','email','whatsapp_number','details','is_interested']

    def __init__(self, *args, **kwargs):
        super(CustomerResponseForm,self).__init__(*args,**kwargs)
        #Charfields
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['whatsapp_number'].widget.attrs['class'] = 'form-control'

        #Textarea
        self.fields['details'].widget.attrs['class'] = 'form-control'
        self.fields['details'].widget.attrs['rows'] = '5'

        

HomeActions/views.py
from django.shortcuts import render,redirect
from .models import HomeActions,ActionBullet,CustomerResponse
from .forms import CustomerResponseForm
from django.contrib import messages

# Create your views here.
def actions(request,name_slug):
    action=HomeActions.objects.get(name_slug=name_slug)
    action_bullets=ActionBullet.objects.filter(Action=action)

    if request.method == 'POST':
        form = CustomerResponseForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['name']
            email=form.cleaned_data['email']
            whatsapp_number=form.cleaned_data['whatsapp_number']
            details=form.cleaned_data['details']
            is_interested=form.cleaned_data['is_interested']

            CustomerResponseObject = CustomerResponse.objects.create(
                name=name,
                email=email,
                whatsapp_number=whatsapp_number,
                details=details,
                is_interested=is_interested,
                service_required=action,
            )

            CustomerResponseObject.save()

            messages.success(request, 'Data Submitted Succesfully!')
        else:
            messages.error(request, 'Invalid Request, Please fill the form properly!')
    else:
        form=CustomerResponseForm()
    context={
        'action':action,
        'action_bullets':action_bullets,
        'form' : form,
    }
    return render(request, "HomeActions/action.html", context)

templates/HomeActions/action.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<!--Style Block-->
<style>
    .parent{
        position: relative;
    }
    .action-element{
        position: absolute;
        left: 50%;
        transform: translate(-50%, -50%);
        font-weight:400;
    }
    
    img{
        margin-top: 55px;
        width: 100%;
        height: auto;
    }

    .pseudo-div{
        width: 100%;
        position: relative;
    }
    .pseudo-div:after{
        content: "";
	    position: absolute;
	    left: 0px;
	    top: -12px;
	    width: 100%;
	    height: 2px;
	    background-color: #fc5a03;
    }
    h5{
        font-weight: 400;
    }
    .form-check .form-check-input:checked ~ .form-check-sign .check {
        background: #fc5a03 !important;
    }

    .btn.btn-primary {
        background-color: #fc5a03 !important;
        border-color: #fc5a03 !important;
    }
    .bmd-label-floating{
        color: rgb(30, 30, 30)!important;
    }
    .form-check-label{
        color: rgb(30, 30, 30)!important;
    }
    #id_is_interested{
      width: 0.8rem;
      height: 0.8rem;
    }
    textarea .form-control{
      background-image: linear-gradient(to top, #fc5a03 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #d2d2d2 1px, rgba(210, 210, 210, 0) 1px);
    }
</style>

<!--Title-->
<title>EdexCare | {{action.name}}</title>

<!-- Meta Description -->

<!--Heading-->
<div class="parent">
  <img src="{% static 'images/Page-title-1.jpg' %}" alt="">
  <h1 class="action-element" style="top: 50%;"><span style="color: #fc5a03;">{{action.name}}</span></h1>
</div>

<!--Main Container -->
<div class="container">
  <div class="section">
    <h3 class="title text-center">About {{action.name}}</h3>
    {% include 'includes/alerts.html' %}
    <h5 class="description pseudo-div" style="color: rgb(30, 30, 30);">

      <!--Description Text-->
      <br>{{action.description}} <br><br>

      <!-- Bullet Points -->
      {% if action_bullets %}
      <strong>Key Points: 
      </strong><br><br>
      {% endif %}

      {% for item in action_bullets %}
        <i class="fas fa-check-square" style="color: #fc5a03;"></i> &nbsp; {{item.bulletpoint}}<br>
      {% endfor %}<br><br>

      <!-- Form Card -->
      <strong>Customer Form: </strong><br> 
      <div class="card">
          <div class="container">
            <form class="contact-form" method="POST" action="{{ action.get_url }}">
              {% csrf_token %} 
                <div class="form-group bmd-form-group">
                  <label class="bmd-label-floating">Name</label>
                  {{form.name}}
                </div>
                <div class="row">
                  <div class="col-md-6 col-lg-6">
                    <div class="form-group bmd-form-group">
                      <label class="bmd-label-floating">Email Address</label>
                      {{form.email}}
                    </div>
                  </div>
                  <div class="col-md-6 col-lg-6">
                    <div class="form-group bmd-form-group">
                      <label class="bmd-label-floating">WhatsApp Number</label>
                      {{form.whatsapp_number}}
                    </div>
                  </div>
                </div>
                <div class="form-group bmd-form-group">
                  <label for="exampleMessage" class="bmd-label-floating">Details of service required</label>
                  {{form.details}}
                </div>
                <div class="row">
                  <div class="col-sm-12 col-12">
                    <div class="form-group bmd-form-group">
                      {{ form.is_interested }} 
                      <label class="form-check-label">I am interested to Sign Up for '{{action.name}}'</label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4 ml-auto mr-auto text-center">
                  <input class="btn btn-primary btn-raised" type="submit" value="submit">
                  </div>
                </div>
              </form>
            </div>
      </div>
    </h5>
  </div>
</div>

{% endblock %}